
CREATE TABLE `Tenant_S` (
  `ID` CHAR(36) NOT NULL COMMENT '',
  `TenantID` CHAR(36) NOT NULL COMMENT '',
  `Name` VARCHAR(50) NOT NULL COMMENT '',
  `Description` VARCHAR(5000) NOT NULL COMMENT '',
  `ValidFrom` DATE NOT NULL DEFAULT '1900-01-01' COMMENT '',
  `ValidUntil` DATE NOT NULL DEFAULT '9999-01-01' COMMENT '',
  `_Modifier` VARCHAR(50) NOT NULL DEFAULT 'UNKNOWN' COMMENT '',
  `_Timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `_Version` INT NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  UNIQUE INDEX `UDX_Tenant_S_TenantID` (`TenantID` ASC)  COMMENT '',
  INDEX `IDX_Tenant_S_ValidFrom-ValidUntil` (`ValidFrom`, `ValidUntil` ASC)  COMMENT '',
  FOREIGN KEY (`TenantID`) REFERENCES `Tenant_H` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE);