DELIMITER $$

CREATE DEFINER=`root`@`%` TRIGGER `TRBI_Person_H` BEFORE INSERT ON `Person_H` FOR EACH ROW
BEGIN
	IF (NEW.ID IS NULL OR NEW.ID= '') THEN
		SET NEW.ID = UUID();
    END IF;
END
$$
DELIMITER ;