
CREATE TABLE `Tenant_H` (
  `ID` CHAR(36) NOT NULL COMMENT '',
  `Code` VARCHAR(50) NOT NULL COMMENT '',
  `_Modifier` VARCHAR(50) NOT NULL DEFAULT 'UNKNOWN' COMMENT '',
  `_Timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `_Version` INT NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  UNIQUE INDEX `UDX_Tenant_H_Code` (`Code` ASC)  COMMENT '');