
DELIMITER $$

CREATE DEFINER=`root`@`%` TRIGGER `TRBI_Tenant_S` BEFORE INSERT ON `Tenant_S` FOR EACH ROW
BEGIN
	IF (NEW.ID IS NULL OR NEW.ID= '') THEN
		SET NEW.ID = UUID();
    END IF;
END
$$
DELIMITER ;