
CREATE TABLE `Person_Identity_S` (
  `ID` CHAR(36) NOT NULL COMMENT '',
  `PersonID` CHAR(36) NOT NULL COMMENT '',
  `Name` VARCHAR(100) DEFAULT '' COMMENT '',
  `Firstname` VARCHAR(100) DEFAULT '' COMMENT '',
  `DisplayName` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '',
  `Info` VARCHAR(5000) NOT NULL DEFAULT '' COMMENT '',
  `_Modifier` VARCHAR(50) NOT NULL DEFAULT 'UNKNOWN' COMMENT '',
  `_Timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `_Version` INT NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  UNIQUE INDEX `UDX_Person_S_PersonID` (`PersonID` ASC)  COMMENT '',
  INDEX `IDX_Person_Identity_S_Name-Firstname` (`Name`, `Firstname` ASC)  COMMENT '',
  FOREIGN KEY (`PersonID`) REFERENCES `Person_H` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE);